version: "3.9"

name: "iffective"

services:
  registry:
    build:
      context: registry
    volumes:
      - data:/data
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /docker-registry/auth/htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    restart: on-failure
  nginx:
    build:
      context: nginx
    volumes:
      - ssl:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
      
volumes:
  ssl:
  data:

networks:
  iffective: