version: "3.9"

name: "iffective"

services:
  nginx-first:
    build:
      context: nginx
      dockerfile: Dockerfile.first
    volumes:
      - www:/var/www/certbot:ro
    ports:
      - "80:80"
    depends_on: 
      - nginx-first
  certbot-first:
    image: certbot/certbot
    volumes:
      - www:/var/www/certbot/:rw
    command: certonly --webroot --webroot-path /var/www/certbot/ --dry-run -d docker.iffective.dk --non-interactive --agree-tos -m mat.lapies@gmail.com
    
volumes:
  www:
  ssl:
     
networks:
  iffective: