version: "3.9"

name: "iffective"

services:
  registry:
    build:
      context: registry
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
  nginx:
    build:
      context: nginx
    volumes:
      - ssl:/etc/nginx/ssl/:ro
    ports:
      - "80:80"
      - "443:443"
      
volumes:
  ssl:

networks:
  iffective: