name: "CD pipeline"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    environment: production
    secrets: |
      "DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}"
    steps:
    - uses: actions/checkout@v3
    - name: Enable letsencrypt
      run: chmod +x init-letsencrypt.sh
    - name: Init letsencrypt
      run: ./init-letsencrypt.sh
    - name: Deploy docker images
      run: docker compose up -d