name: "First run"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, production]
    steps:
    - uses: actions/checkout@v3
    - name: Build docker images
      run: docker compose -f docker-compose-first.yaml build --no-cache
    - name: Prepare cerificates
      run: docker compose -f docker-compose-first.yaml up