name: Mirror run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  mirror:
    name: Mirror Images
    runs-on: ubuntu-latest
    environment: production
    strategy:
        matrix:
          image: ${{ variables.IMAGES }}
    steps:
      - name: Pull Image from Docker Hub
        run: docker pull ${{ matrix.image }}
    
      - name: Tag Image
        run: docker tag ${{ matrix.image }} docker.iffective.dk/${{ matrix.image }}
      
      - name: Login to container registry
        run: docker login docker.iffective.dk -u docker -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Push Image
        run: docker push docker.iffective.dk/${{ matrix.image }}
        
      - name: Logout from container registry
        run: docker logout