name: "Normal run"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, production]
    steps:
    - uses: actions/checkout@v3
    - name: Build docker images
      run: docker compose build --no-cache
    - name: Deploy docker images
      run: docker compose up -d