name: "Normal run"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, production]
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Build docker images
      run: docker compose build --no-cache
    - name: Generate htpasswd
      run: docker compose run --entrypoint="htpasswdhttpd:2-Bbnchtpasswddocker${{ secrets.DOCKER_PASSWORD }}" registry
    - name: Deploy docker images
      run: docker compose up -d